import {
  HiOutlinePlus, HiOutlineMinus, HiOutlineXMark, HiOutlineCheck, HiOutlineMagnifyingGlass,
  HiOutlineBell, HiOutlineUser, HiOutlineChevronRight, HiOutlineBars3, HiOutlineArrowRightOnRectangle,
  HiOutlineHome, HiOutlineDocumentText, HiOutlineClipboardDocumentList, HiOutlineCog6Tooth,
  HiOutlineChartBar, HiOutlineCube, HiOutlineTruck, HiOutlineEye, HiOutlinePencilSquare,
  HiOutlineTrash, HiOutlineExclamationTriangle, HiOutlineInformationCircle, HiOutlineCheckCircle,
  HiOutlineXCircle, HiOutlineClock, HiOutlineArrowTrendingUp, HiOutlineUsers, HiOutlineTag,
  HiOutlineCreditCard, HiOutlinePrinter, HiOutlinePaperAirplane, HiOutlineArrowPath,
  HiOutlineFolder, HiOutlineEllipsisHorizontal, HiOutlineSquares2X2, HiOutlineListBullet,
  HiOutlineWrenchScrewdriver, HiOutlineSparkles, HiOutlineShieldCheck, HiOutlineArrowDownTray,
  HiOutlineCalendarDays, HiOutlineCurrencyDollar, HiOutlineBuildingOffice2, HiOutlineMapPin,
  HiOutlinePhone, HiOutlineEnvelope, HiOutlineHashtag, HiOutlinePhoto, HiOutlineRocketLaunch,
} from "react-icons/hi2";
import {
  LuPalette, LuCrop, LuImage, LuSpellCheck2, LuThumbsUp, LuSticker, LuFlag,
  LuScrollText, LuPanelTop, LuFileImage, LuTextCursorInput, LuRuler, LuCaseSensitive,
  LuScanLine, LuScanFace, LuScanText, LuLayoutDashboard, LuFileStack, LuChartBar,
  LuPackage, LuWarehouse, LuClipboardCheck, LuCircleOff, LuCircleDot, LuSearchX,
  LuCircle, LuFilter, LuSettings2, LuPanelLeftClose, LuSun, LuMoon, LuHand,
  LuHardHat, LuBox, LuShirt, LuSofa, LuContainer, LuColumns2, LuRows2,
} from "react-icons/lu";

const icons = {
  add: HiOutlinePlus,
  add_box: HiOutlinePlus,
  remove: HiOutlineMinus,
  close: HiOutlineXMark,
  check: HiOutlineCheck,
  search: HiOutlineMagnifyingGlass,
  notifications: HiOutlineBell,
  person: HiOutlineUser,
  person_add: HiOutlineUser,
  chevron_right: HiOutlineChevronRight,
  menu: HiOutlineBars3,
  logout: HiOutlineArrowRightOnRectangle,
  dashboard: LuLayoutDashboard,
  request_quote: HiOutlineDocumentText,
  precision_manufacturing: HiOutlineClipboardDocumentList,
  settings_suggest: HiOutlineSparkles,
  print: HiOutlinePrinter,
  handyman: HiOutlineWrenchScrewdriver,
  inventory_2: LuWarehouse,
  inventory: LuPackage,
  account_balance_wallet: HiOutlineCreditCard,
  analytics: LuChartBar,
  verified: HiOutlineShieldCheck,
  settings: HiOutlineCog6Tooth,
  description: HiOutlineDocumentText,
  format_color_fill: LuPalette,
  flag: LuFlag,
  sticker: LuSticker,
  view_column: LuColumns2,
  warning: HiOutlineExclamationTriangle,
  info: HiOutlineInformationCircle,
  check_circle: HiOutlineCheckCircle,
  cancel: HiOutlineXCircle,
  pending: HiOutlineClock,
  checklist: HiOutlineClipboardDocumentList,
  block: HiOutlineXCircle,
  trending_up: HiOutlineArrowTrendingUp,
  groups: HiOutlineUsers,
  construction: HiOutlineWrenchScrewdriver,
  content_cut: HiOutlineHashtag,
  numbers: HiOutlineHashtag,
  conversion_path: HiOutlineArrowPath,
  chat: HiOutlinePaperAirplane,
  edit: HiOutlinePencilSquare,
  edit_note: HiOutlinePencilSquare,
  delete: HiOutlineTrash,
  visibility: HiOutlineEye,
  search_off: LuSearchX,
  view_list: HiOutlineListBullet,
  person_search: HiOutlineUser,
  local_shipping: HiOutlineTruck,
  rule: HiOutlineClipboardDocumentList,
  preview: LuScanLine,
  file_present: HiOutlineDocumentText,
  straighten: LuRuler,
  crop: LuCrop,
  palette: LuPalette,
  text_fields: LuCaseSensitive,
  image: HiOutlinePhoto,
  spellcheck: LuSpellCheck2,
  thumb_up: HiOutlineCheckCircle,
  light_mode: LuSun,
  dark_mode: LuMoon,
  home: HiOutlineHome,
  folder: HiOutlineFolder,
  more: HiOutlineEllipsisHorizontal,
  grid: HiOutlineSquares2X2,
  list: HiOutlineListBullet,
  download: HiOutlineArrowDownTray,
  calendar: HiOutlineCalendarDays,
  currency: HiOutlineCurrencyDollar,
  building: HiOutlineBuildingOffice2,
  location: HiOutlineMapPin,
  phone: HiOutlinePhone,
  email: HiOutlineEnvelope,
  photo: HiOutlinePhoto,
  rocket: HiOutlineRocketLaunch,
  tag: HiOutlineTag,
  clock: HiOutlineClock,
  filter: LuFilter,
  settings2: LuSettings2,
  sidebar: LuPanelLeftClose,
  check_all: HiOutlineClipboardDocumentList,
  radio_button_unchecked: LuCircle,
  circle_off: LuCircleOff,
  circle_dot: LuCircleDot,
  colorize: LuPalette,
  content_paste: HiOutlineClipboardDocumentList,
  fact_check: HiOutlineClipboardDocumentList,
  spellcheck_2: LuSpellCheck2,
  task: HiOutlineClipboardDocumentList,
  workspace: HiOutlineSquares2X2,
  scan: LuScanLine,
  scan_text: LuScanText,
  scan_face: LuScanFace,
  file_image: LuFileImage,
  text_cursor: LuTextCursorInput,
  ruler: LuRuler,
};

export default function Icon({ name, className = "", ...props }) {
  const Component = icons[name] || HiOutlineEllipsisHorizontal;
  return <Component className={className} {...props} />;
}
